[package]
name = "wasm-part"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "Document"] }
serde = { version = "1.0", features = ["derive"] }
num-bigint = "0.4"
