[package]
name = "util-fns-wasm"
edition = "2024"
version = "0.0.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "Document"] }
num-bigint = "0.4"
